version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=base.settings

  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

volumes:
  redis_data:
  postgres_data:
