version: '3.8'

services:
  web:
    command: bash -c "./start_server.sh"
    ports:
      - "8000:8000"
    env_file:
      - .env.prod

  celery:
    build: .
    command: bash -c "uv run celery -A base worker --loglevel=INFO"
    env_file:
      - .env.prod
