# Generated by Django 5.0.7 on 2024-08-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
