# Generated by Django 5.0.7 on 2024-09-02 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField(auto_now_add=True)),
                ('winner', models.CharField(blank=True, max_length=255, null=True)),
                ('game_status', models.CharField(choices=[('playing', 'Playing'), ('finished', 'Finished'), ('canceled', 'Canceled'), ('surrendered', 'Surrendered')], max_length=255)),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_player', to=settings.AUTH_USER_MODEL)),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_player', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GameMatch',
                'verbose_name_plural': 'GameMatches',
            },
        ),
        migrations.CreateModel(
            name='GameMatchMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_color', models.CharField(choices=[('white', 'White'), ('black', 'Black')], max_length=6)),
                ('piece_type', models.CharField(choices=[('normal', 'Normal'), ('dama', 'Dama')], max_length=6)),
                ('origin_x', models.IntegerField()),
                ('origin_y', models.IntegerField()),
                ('destiny_x', models.IntegerField()),
                ('destiny_y', models.IntegerField()),
                ('state_before_move', models.JSONField()),
                ('state_after_move', models.JSONField()),
                ('was_capture', models.BooleanField()),
                ('game_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameroom.gamematch')),
            ],
            options={
                'verbose_name': 'GameMatchMovements',
                'verbose_name_plural': 'GameMatchMovements',
            },
        ),
    ]
