# Generated by Django 5.0.7 on 2024-09-04 22:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamematch',
            name='game_id',
            field=models.UUIDField(default=uuid.UUID('3564f360-bccc-4c16-b0dd-5e4847206a2c'), editable=False),
        ),
    ]
