# Generated by Django 5.0.7 on 2024-09-05 14:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0002_gamematch_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamematch',
            name='game_id',
            field=models.UUIDField(default=uuid.UUID('baaf7a07-f82f-473e-8704-85f53ab27fca'), editable=False),
        ),
    ]
