# Generated by Django 5.0.7 on 2024-09-05 20:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0003_alter_gamematch_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamematch',
            name='game_id',
            field=models.UUIDField(default=uuid.UUID('536709ba-ae0c-4d7d-8587-4065509660e1'), editable=False),
        ),
    ]
