# Generated by Django 5.0.7 on 2024-09-06 16:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0004_alter_gamematch_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamematch',
            name='game_id',
            field=models.UUIDField(default=uuid.UUID('a4002ad9-f7fa-453f-9d2a-b6f07981ab46'), editable=False),
        ),
    ]
