# Generated by Django 5.0.7 on 2024-09-07 14:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0005_alter_gamematch_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamematch',
            name='game_id',
            field=models.UUIDField(default=uuid.UUID('994a9187-d727-404e-9a84-6fd57d1cc1e9'), editable=False),
        ),
    ]
