# Generated by Django 5.0.7 on 2024-09-08 16:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0006_alter_gamematch_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamematch',
            name='game_id',
            field=models.UUIDField(default=uuid.UUID('90c6609f-cca0-429e-9132-7bebd1713715'), editable=False),
        ),
    ]
