# Generated by Django 5.0.7 on 2024-09-09 14:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0007_alter_gamematch_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamematch',
            name='game_id',
            field=models.UUIDField(default=uuid.UUID('6d1aafa9-8431-445b-9295-86cb0eea62ad'), editable=False),
        ),
    ]
