# Generated by Django 5.0.7 on 2025-01-03 22:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0008_alter_gamematch_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamematch',
            name='game_id',
            field=models.UUIDField(default=uuid.UUID('1f1515ee-c685-4359-a76e-ec547aadb3e1'), editable=False),
        ),
    ]
