# Generated by Django 5.0.7 on 2025-01-03 22:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0009_alter_gamematch_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamematch',
            name='game_id',
            field=models.UUIDField(default=uuid.UUID('5c6a600c-aa77-4454-b5bb-e4d0d955ff3e'), editable=False),
        ),
    ]
