# Generated by Django 5.0.7 on 2025-01-03 23:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0010_alter_gamematch_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamematch',
            name='game_id',
            field=models.UUIDField(default=uuid.UUID('c3be6967-aed2-4936-aaa8-14056ecfc4b1'), editable=False),
        ),
    ]
