# Generated by Django 5.0.7 on 2025-01-03 23:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0011_alter_gamematch_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamematch',
            name='game_id',
            field=models.UUIDField(default=uuid.UUID('58d570e0-7192-4b7c-a844-f04a77a3d357'), editable=False),
        ),
    ]
