# Generated by Django 5.0.7 on 2025-01-03 23:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0012_alter_gamematch_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamematch',
            name='game_id',
            field=models.UUIDField(default=uuid.UUID('6fdc34cf-b4ce-4bf4-a7b3-f279beadced9'), editable=False),
        ),
    ]
