name: Deploy Django App

on:
  push:
    branches:
      - main  # Altere para o branch de deploy se necessário

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH Key
      env:
        PRIVATE_SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
      run: |
        # Cria o diretório ~/.ssh se não existir
        mkdir -p ~/.ssh

        # Salva a chave privada em um arquivo
        echo "$PRIVATE_SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        # Inicia o agente SSH e adiciona a chave privada
        ssh-keygen -p -f ~/.ssh/id_rsa
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa
    - name: Deploy to VPS
      env:
        VPS_HOST: ${{ secrets.VPS_HOST }}
        VPS_USER: ${{ secrets.VPS_USER }}
        APP_PATH: ${{ secrets.APP_PATH }}
        ENV_CONTENT: ${{ secrets.ENV_CONTENT }}
        ENV_DEV_CONTENT: ${{ secrets.ENV_DEV_CONTENT }}
        ENV_PROD_CONTENT: ${{ secrets.ENV_PROD_CONTENT }}
        NGINX_CONF: ${{ secrets.NGINX_CONF }}
      run: |
        # Conecta via SSH e faz o deploy usando Docker Compose
        ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << EOF
          cd $APP_PATH
          git pull origin main
          echo "$NGINX_CONF" > cg-backend
          echo "$ENV_CONTENT" > .env
          echo "$ENV_DEV_CONTENT" > .env.dev
          echo "$ENV_PROD_CONTENT" > .env.prod
          sudo docker compose -f docker-compose.yml -f docker-compose.prod.yml down
          sudo docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build
          sudo cp cg-backend /etc/nginx/sites-enabled/
          sudo nginx -t
          sudo systemctl restart nginx
        EOF

    - name: Cleanup
      run: |
        # Remove a chave privada após o deploy
        rm ~/.ssh/id_rsa
